[package]
name = "neoshell"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "neoshell"
path = "src/main.rs"
test = false

[lib]
name = "neoshell_lib"
path = "src/lib.rs"

[dependencies]
libneodos = { path = "../../libneodos" }
libneoutil = { path = "../../libneoutil" }

[profile.release]
panic = "abort"
opt-level = 3
lto = true
debug = false

[profile.dev]
panic = "abort"
