use std::env;
use std::fs;

fn resolve_level(env_var: &str, default: &str) -> String {
    match env::var(env_var) {
        Ok(val) => val.to_uppercase(),
        Err(_) => default.to_uppercase(),
    }
}

fn level_to_u8(s: &str) -> u8 {
    match s {
        "ERROR" => 0,
        "WARN" => 1,
        "INFO" => 2,
        "DEBUG" => 3,
        "TRACE" => 4,
        _ => 2,
    }
}

fn main() {
    let default_level = env::var("LOG_DEFAULT").unwrap_or_else(|_| "DEBUG".to_string());

    let default = default_level.to_uppercase();

    let subsystems: &[(&str, &str)] = &[
        ("KERNEL", &default),
        ("NET", &resolve_level("LOG_NET", &default)),
        ("SCHED", &resolve_level("LOG_SCHED", &default)),
        ("DRIVER", &resolve_level("LOG_DRIVER", &default)),
        ("POWER", &resolve_level("LOG_POWER", &default)),
        ("SERVICES", &resolve_level("LOG_SERVICES", &default)),
        ("CM", &resolve_level("LOG_CM", &default)),
        ("OBJECT", &resolve_level("LOG_OBJECT", &default)),
        ("SYSCALL", &resolve_level("LOG_SYSCALL", &default)),
        ("KBD", &resolve_level("LOG_KBD", &default)),
        ("INPUT", &resolve_level("LOG_INPUT", &default)),
        ("VIRTIO", &resolve_level("LOG_VIRTIO", &default)),
        ("TIMERS", &resolve_level("LOG_TIMERS", &default)),
        ("INTERRUPTS", &resolve_level("LOG_INTERRUPTS", &default)),
        ("EXCEPTION", &resolve_level("LOG_EXCEPTION", &default)),
        ("SECURITY", &resolve_level("LOG_SECURITY", &default)),
        ("FAT32", &resolve_level("LOG_FAT32", &default)),
        ("HOTRELOAD", &resolve_level("LOG_HOTRELOAD", &default)),
        ("ISOLATION", &resolve_level("LOG_ISOLATION", &default)),
        ("NEM", &resolve_level("LOG_NEM", &default)),
        ("NVME", &resolve_level("LOG_NVME", &default)),
        ("PCI", &resolve_level("LOG_PCI", &default)),
        ("SLAB", &resolve_level("LOG_SLAB", &default)),
        ("ELF", &resolve_level("LOG_ELF", &default)),
        ("NXL", &resolve_level("LOG_NXL", &default)),
        ("VFS", &resolve_level("LOG_VFS", &default)),
        ("FS", &resolve_level("LOG_FS", &default)),
        ("WATCHDOG", &resolve_level("LOG_WATCHDOG", &default)),
        ("BOOT", &resolve_level("LOG_BOOT", &default)),
        ("TEST", &resolve_level("LOG_TEST", &default)),
        ("MEMORY", &resolve_level("LOG_MEMORY", &default)),
        ("DNS", &resolve_level("LOG_DNS", &default)),
        ("ARP", &resolve_level("LOG_ARP", &default)),
        ("ICMP", &resolve_level("LOG_ICMP", &default)),
        ("SEH", &resolve_level("LOG_SEH", &default)),
        ("APIC", &resolve_level("LOG_APIC", &default)),
        ("HPET", &resolve_level("LOG_HPET", &default)),
        ("IOAPIC", &resolve_level("LOG_IOAPIC", &default)),
        ("MSI", &resolve_level("LOG_MSI", &default)),
        ("PS2", &resolve_level("LOG_PS2", &default)),
        ("ATA", &resolve_level("LOG_ATA", &default)),
        ("AHCI", &resolve_level("LOG_AHCI", &default)),
        ("BENCH", &resolve_level("LOG_BENCH", &default)),
        ("INIT", &resolve_level("LOG_INIT", &default)),
        ("USER", &resolve_level("LOG_USER", &default)),
        ("STORAGE", &resolve_level("LOG_STORAGE", &default)),
    ];

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = std::path::Path::new(&out_dir).join("log_config.rs");

    let mut content = String::new();
    content.push_str("// Auto-generated by build.rs — do not edit\n");
    content.push_str("// Configurable via environment variables:\n");
    content.push_str("//   LOG_DEFAULT  — default level for all subsystems\n");
    content.push_str("//   LOG_NET      — per-subsystem override (NET, SCHED, DRIVER, etc.)\n");
    content.push_str("// Levels: ERROR=0 WARN=1 INFO=2 DEBUG=3 TRACE=4\n");
    content.push_str("\n");

    for (name, level) in subsystems {
        let lvl = level_to_u8(level);
        content.push_str(&format!(
            "pub const BUILD_{}_LEVEL: u8 = {}u8;\n",
            name.to_uppercase(), lvl
        ));
    }

    // Emit runtime counter of total subsystems
    content.push_str(&format!(
        "\npub const LOG_SUBSYS_COUNT: usize = {};\n",
        subsystems.len()
    ));

    // Emit names slice for runtime display
    content.push_str("pub const LOG_SUBSYS_NAMES: &[&str] = &[\n");
    for (name, _) in subsystems {
        content.push_str(&format!("    \"{}\",\n", name));
    }
    content.push_str("];\n");

    fs::write(&dest, &content).unwrap();
    println!("cargo:rerun-if-env-changed=LOG_DEFAULT");
    for (name, _) in subsystems {
        println!("cargo:rerun-if-env-changed=LOG_{}", name);
    }
}
