#!/usr/bin/env bash
# Build + test convenience wrapper.
#
# `neodev test` loads the root `kernel.elf`, which is (re)generated by
# `neodev build` (it compiles the kernel in the release profile and copies
# target/<target>/release/neodos_kernel -> kernel.elf). Always build the image
# before testing so the suite runs the current kernel.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "[build-test] neodev build --quick --image..."
neodev build --quick --image

echo "[build-test] neodev test..."
neodev test "$@"
