[package]
name = "neolocale"
version = "0.1.0"
edition = "2021"
description = "NLT file validator and inspector (host tool)"

[[bin]]
name = "neolocale"
path = "src/main.rs"

[dependencies]
libnlt = { path = "../../libnlt", features = ["signatures"] }

[profile.release]
panic = "abort"
opt-level = 3
lto = true
debug = false

[profile.dev]
panic = "abort"
